### ISSUE TITLE
Limit position setpoint maximum distance from quad

### ISSUE THREAD

**Issue by t0ni0** [elikos/Firmware#5]
The actual position controller was not designed to take position setpoints very far from the quadcopter. Currently when we give it a 5 m setpoint the quad will agressively tilt in the direction it wants to go. This results in poor optical flow and loss of precision which would add up with time...

The firmware needs to store the actual setpoint but limit the error in position to a smaller value such as 1m. This would have be tunable with a new parameter.

**Comment by andre-nguyen** [comment]
Doubt this issue is valid anymore, if our problem was the agressivity of the quad on far off setpoints, we can play with MPC_TILTMAX_AIR https://pixhawk.org/firmware/parameters
